version: "3.9"

services:
  test_db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}
      POSTGRES_DB: ${TEST_DATABASE_NAME}
    volumes:
      - data:/var/lib/postgresql/test_db
    ports:
      - "5433:5432"

volumes:
  data: {}
